services:
  mysql:
    image: mysql:8.4
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: calmspace_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    image: pavaniedirisinghe/calmspace-backend:latest
    container_name: backend_c
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: calmspace_db
    ports:
      - "5000:5000"
    command: sh -c "sleep 10 && node Server.js"   

  frontend:
    build: ./frontend
    image: pavaniedirisinghe/calmspace-frontend:latest 
    container_name: frontend_c
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
